theme: jekyll-theme-minimal
title: Spatialising Sarah Barclay Johnson's travelogue around Jerusalem (1858)
description: FDH G8, 2023
#show_downloads: True
#navigation:
#  - title: Home
#    url: /
#  - title: Bibliography
#    url: bibliography
